// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheChopClub.Models;

#nullable disable

namespace TheChopClub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TheChopClub.Models.Barbershop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Barbershops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua de Santa Catarina, 123",
                            City = "Porto",
                            CreatedAt = new DateTime(2026, 3, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Barbearia tradicional no coração do Porto",
                            IsPremium = true,
                            Name = "Classic Cuts Porto",
                            Phone = "+351 222 123 456",
                            Rating = 4.8m,
                            TotalReviews = 127,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Av. da Liberdade, 456",
                            City = "Lisboa",
                            CreatedAt = new DateTime(2026, 4, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Cortes de excelência na capital",
                            IsPremium = true,
                            Name = "Master Cuts Lisboa",
                            Phone = "+351 211 234 567",
                            Rating = 4.9m,
                            TotalReviews = 203,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Address = "Praça da República, 789",
                            City = "Braga",
                            CreatedAt = new DateTime(2026, 5, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Estilo urbano e moderno",
                            IsPremium = false,
                            Name = "Urban Barbershop",
                            Phone = "+351 253 345 678",
                            Rating = 4.7m,
                            TotalReviews = 89,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rua da Sofia, 321",
                            City = "Coimbra",
                            CreatedAt = new DateTime(2026, 6, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Experiência de barbeiro de luxo",
                            IsPremium = true,
                            Name = "The Barber Lounge",
                            Phone = "+351 239 456 789",
                            Rating = 4.6m,
                            TotalReviews = 64,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rua João Mendonça, 654",
                            City = "Aveiro",
                            CreatedAt = new DateTime(2026, 7, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Cortes precisos e estilo impecável",
                            IsPremium = false,
                            Name = "Sharp Cuts",
                            Phone = "+351 234 567 890",
                            Rating = 4.5m,
                            TotalReviews = 45,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarbershopId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BarbershopId", "Date", "Time");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TheChopClub.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Trabalho incrível! Ficou perfeito!",
                            CreatedAt = new DateTime(2026, 8, 8, 16, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            Content = "Esse degradê está top demais!",
                            CreatedAt = new DateTime(2026, 8, 8, 18, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Content = "Qualidade impecável como sempre!",
                            CreatedAt = new DateTime(2026, 8, 8, 21, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "É por isso que és campeão!",
                            CreatedAt = new DateTime(2026, 8, 8, 11, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Content = "Já marquei horário!",
                            CreatedAt = new DateTime(2026, 8, 8, 14, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            Content = "Criatividade no ponto!",
                            CreatedAt = new DateTime(2026, 8, 8, 20, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Quero fazer um igual!",
                            CreatedAt = new DateTime(2026, 8, 8, 22, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 6,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Content = "Vale cada cêntimo!",
                            CreatedAt = new DateTime(2026, 8, 8, 23, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Content = "Como faço para me inscrever?",
                            CreatedAt = new DateTime(2026, 8, 8, 6, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 12,
                            UserId = 7
                        },
                        new
                        {
                            Id = 10,
                            Content = "Preço do workshop?",
                            CreatedAt = new DateTime(2026, 8, 8, 8, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 12,
                            UserId = 8
                        },
                        new
                        {
                            Id = 11,
                            Content = "Já marquei para sábado!",
                            CreatedAt = new DateTime(2026, 8, 9, 0, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 14,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Promoção top!",
                            CreatedAt = new DateTime(2026, 8, 9, 1, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            PostId = 14,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarbershopId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BarbershopId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 8, 8, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Trabalho de hoje! Fade suave com degradê perfeito",
                            ImageUrl = "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800",
                            Likes = 145,
                            Title = "Fade Clássico com Barba Alinhada",
                            Views = 890
                        },
                        new
                        {
                            Id = 2,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 8, 6, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Para o cliente que valoriza elegância",
                            ImageUrl = "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800",
                            Likes = 98,
                            Title = "Corte Executivo Premium",
                            Views = 654
                        },
                        new
                        {
                            Id = 3,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 8, 4, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Antes e depois impressionante!",
                            ImageUrl = "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800",
                            Likes = 203,
                            Title = "Transformação Completa",
                            Views = 1245
                        },
                        new
                        {
                            Id = 4,
                            BarbershopId = 2,
                            CreatedAt = new DateTime(2026, 8, 7, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Trabalho premiado! Precisão milimétrica",
                            ImageUrl = "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800",
                            Likes = 287,
                            Title = "Fade Diamante - Técnica Avançada",
                            Views = 1567
                        },
                        new
                        {
                            Id = 5,
                            BarbershopId = 2,
                            CreatedAt = new DateTime(2026, 8, 5, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Técnica tradicional com toques modernos",
                            ImageUrl = "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800",
                            Likes = 176,
                            Title = "Barba Esculpida - Arte Pura",
                            Views = 987
                        },
                        new
                        {
                            Id = 6,
                            BarbershopId = 3,
                            CreatedAt = new DateTime(2026, 8, 8, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Arte e estilo em cada detalhe",
                            ImageUrl = "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800",
                            Likes = 134,
                            Title = "Design Capilar Personalizado",
                            Views = 756
                        },
                        new
                        {
                            Id = 7,
                            BarbershopId = 3,
                            CreatedAt = new DateTime(2026, 8, 3, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Estilo urbano que marca presença",
                            ImageUrl = "https://images.unsplash.com/photo-1620331311520-246422fd82f9?w=800",
                            Likes = 89,
                            Title = "Low Fade + Design Lateral",
                            Views = 543
                        },
                        new
                        {
                            Id = 8,
                            BarbershopId = 4,
                            CreatedAt = new DateTime(2026, 8, 8, 14, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Corte + Barba + Tratamento facial",
                            ImageUrl = "https://images.unsplash.com/photo-1621274790572-7c32596bc67f?w=800",
                            Likes = 167,
                            Title = "Experiência Premium Completa",
                            Views = 923
                        },
                        new
                        {
                            Id = 9,
                            BarbershopId = 4,
                            CreatedAt = new DateTime(2026, 8, 2, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Elegância atemporal",
                            ImageUrl = "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800",
                            Likes = 112,
                            Title = "Corte Clássico Refinado",
                            Views = 687
                        },
                        new
                        {
                            Id = 10,
                            BarbershopId = 5,
                            CreatedAt = new DateTime(2026, 8, 7, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Corte moderno e versátil",
                            ImageUrl = "https://images.unsplash.com/photo-1599351431613-75d5c1f95541?w=800",
                            Likes = 78,
                            Title = "Mid Fade Texturizado",
                            Views = 456
                        },
                        new
                        {
                            Id = 11,
                            BarbershopId = 5,
                            CreatedAt = new DateTime(2026, 8, 1, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Suavidade e precisão",
                            ImageUrl = "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800",
                            Likes = 92,
                            Title = "Degradê Perfeito",
                            Views = 534
                        },
                        new
                        {
                            Id = 12,
                            BarbershopId = 2,
                            CreatedAt = new DateTime(2026, 8, 6, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Aprenda com os melhores!",
                            ImageUrl = "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800",
                            Likes = 234,
                            Title = "Curso de Barbering - Próxima Turma",
                            Views = 1890
                        },
                        new
                        {
                            Id = 13,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 8, 8, 20, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Atendimento exclusivo",
                            ImageUrl = "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=800",
                            Likes = 156,
                            Title = "Cliente VIP - Tratamento Especial",
                            Views = 876
                        },
                        new
                        {
                            Id = 14,
                            BarbershopId = 3,
                            CreatedAt = new DateTime(2026, 8, 8, 8, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Fim de semana com desconto!",
                            ImageUrl = "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800",
                            Likes = 267,
                            Title = "Promo Weekend - 20% OFF",
                            Views = 1456
                        },
                        new
                        {
                            Id = 15,
                            BarbershopId = 4,
                            CreatedAt = new DateTime(2026, 8, 5, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "A melhor pomada para o teu estilo",
                            ImageUrl = "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800",
                            Likes = 98,
                            Title = "Produto do Mês - Pomada Premium",
                            Views = 678
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarbershopId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BarbershopId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 6, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Fixação forte, acabamento mate",
                            ImageUrl = "https://images.unsplash.com/photo-1621607512214-68297480165e?w=400",
                            IsActive = true,
                            Name = "Pomada Matte Premium",
                            Price = 18.90m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            BarbershopId = 1,
                            CreatedAt = new DateTime(2026, 6, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Hidratação profunda e brilho natural",
                            ImageUrl = "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=400",
                            IsActive = true,
                            Name = "Óleo para Barba Excellence",
                            Price = 22.50m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            BarbershopId = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Óleo + Bálsamo + Pente",
                            ImageUrl = "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=400",
                            IsActive = true,
                            Name = "Kit Barba Completo Pro",
                            Price = 45.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            BarbershopId = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Brilho intenso e fixação duradora",
                            ImageUrl = "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=400",
                            IsActive = true,
                            Name = "Cera Modeladora High Shine",
                            Price = 16.90m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            BarbershopId = 3,
                            CreatedAt = new DateTime(2026, 6, 25, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Volume e textura instantâneos",
                            ImageUrl = "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400",
                            IsActive = true,
                            Name = "Spray Texturizador Urban",
                            Price = 19.90m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarbershopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BarbershopId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarbershopId = 1,
                            Comment = "Excelente profissional! Corte impecável!",
                            CreatedAt = new DateTime(2026, 7, 30, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            BarbershopId = 1,
                            Comment = "Melhor barbeiro do Porto!",
                            CreatedAt = new DateTime(2026, 7, 25, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            BarbershopId = 1,
                            Comment = "Muito bom serviço!",
                            CreatedAt = new DateTime(2026, 7, 20, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BarbershopId = 2,
                            Comment = "Campeão nacional não é à toa!",
                            CreatedAt = new DateTime(2026, 7, 28, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            BarbershopId = 2,
                            Comment = "Perfeição absoluta!",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            BarbershopId = 3,
                            Comment = "Designs capilares incríveis!",
                            CreatedAt = new DateTime(2026, 8, 1, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            BarbershopId = 3,
                            Comment = "Muito bom! Ambiente descontraído!",
                            CreatedAt = new DateTime(2026, 7, 26, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BarbershopId = 4,
                            Comment = "Experiência premium verdadeira!",
                            CreatedAt = new DateTime(2026, 8, 3, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BarbershopId = 4,
                            Comment = "Ambiente relaxante!",
                            CreatedAt = new DateTime(2026, 7, 24, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            BarbershopId = 5,
                            Comment = "Rapidez e qualidade!",
                            CreatedAt = new DateTime(2026, 8, 4, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            BarbershopId = 5,
                            Comment = "Bom custo-benefício!",
                            CreatedAt = new DateTime(2026, 7, 29, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Rating = 4,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Administrador da plataforma",
                            CreatedAt = new DateTime(2026, 2, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "admin@chopclub.com",
                            Location = "Porto, Portugal",
                            PasswordHash = "$2a$11$N.KlbhLVtQ0ULT22Dw9pjOHcJb3hFQQIRdW.rA254538HUzYoVks2",
                            UserType = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Barbeiro profissional há 15 anos",
                            CreatedAt = new DateTime(2026, 3, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "joao@classiccuts.com",
                            Location = "Porto, Portugal",
                            PasswordHash = "$2a$11$s.gCpqF4nN1.XXK.9eIEqOferET0SLVcYvBcGT2yip7RXG3E6R9H.",
                            UserType = 1,
                            Username = "joao_barber"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Mestre barbeiro. Campeão nacional 2023",
                            CreatedAt = new DateTime(2026, 4, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "ricardo@mastercuts.com",
                            Location = "Lisboa, Portugal",
                            PasswordHash = "$2a$11$OE4ncSNG4xEZ3Ry4/65xTOQSg8vdKnxzGTFr0hC..ygciSOZC7gve",
                            UserType = 1,
                            Username = "ricardo_silva"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Especialista em fades e designs",
                            CreatedAt = new DateTime(2026, 5, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "carlos@urbanbarbershop.com",
                            Location = "Braga, Portugal",
                            PasswordHash = "$2a$11$kKWWgPB777j6fpJLLBUV1OErn6GHr5qGV464xd/06jDWYoaIZNuH2",
                            UserType = 1,
                            Username = "carlos_styles"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Barba e cabelo com técnicas tradicionais",
                            CreatedAt = new DateTime(2026, 6, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "miguel@thebarberlounge.com",
                            Location = "Coimbra, Portugal",
                            PasswordHash = "$2a$11$7oK.M96ptP.G6Sp4/vGSc.4YDk6fd1zQBoBEQrOTP2lZUw8gE.1ea",
                            UserType = 1,
                            Username = "miguel_premium"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Cortes modernos e clássicos",
                            CreatedAt = new DateTime(2026, 7, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "andre@sharpcuts.com",
                            Location = "Aveiro, Portugal",
                            PasswordHash = "$2a$11$EvKAMiE/VnKOUGri7bUEmOOVK8ZOjpY.Tk1b1LSlQ0vSUXWeGeKc6",
                            UserType = 1,
                            Username = "andre_cuts"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Apaixonado por bons cortes",
                            CreatedAt = new DateTime(2026, 6, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "pedro@email.com",
                            Location = "Porto, Portugal",
                            PasswordHash = "$2a$11$a/jrDM6IGsZR3cnJlr1uP.y1m6FsTeB5S7pslgTt16gNFGrd2svaW",
                            UserType = 0,
                            Username = "pedro_cliente"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Cliente regular",
                            CreatedAt = new DateTime(2026, 7, 9, 2, 32, 28, 316, DateTimeKind.Utc).AddTicks(9512),
                            Email = "tiago@email.com",
                            Location = "Lisboa, Portugal",
                            PasswordHash = "$2a$11$cMlDv2WuwlVCriC2UBV0L.kI8IvLhTmo/4Ph4KWM1l6fRItIBQpl6",
                            UserType = 0,
                            Username = "tiago_sousa"
                        });
                });

            modelBuilder.Entity("TheChopClub.Models.Barbershop", b =>
                {
                    b.HasOne("TheChopClub.Models.User", "User")
                        .WithOne("Barbershop")
                        .HasForeignKey("TheChopClub.Models.Barbershop", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheChopClub.Models.Booking", b =>
                {
                    b.HasOne("TheChopClub.Models.Barbershop", "Barbershop")
                        .WithMany()
                        .HasForeignKey("BarbershopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheChopClub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbershop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheChopClub.Models.Comment", b =>
                {
                    b.HasOne("TheChopClub.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheChopClub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheChopClub.Models.Post", b =>
                {
                    b.HasOne("TheChopClub.Models.Barbershop", "Barbershop")
                        .WithMany("Posts")
                        .HasForeignKey("BarbershopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbershop");
                });

            modelBuilder.Entity("TheChopClub.Models.Product", b =>
                {
                    b.HasOne("TheChopClub.Models.Barbershop", "Barbershop")
                        .WithMany("Products")
                        .HasForeignKey("BarbershopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbershop");
                });

            modelBuilder.Entity("TheChopClub.Models.Review", b =>
                {
                    b.HasOne("TheChopClub.Models.Barbershop", "Barbershop")
                        .WithMany("Reviews")
                        .HasForeignKey("BarbershopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheChopClub.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbershop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheChopClub.Models.Barbershop", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TheChopClub.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TheChopClub.Models.User", b =>
                {
                    b.Navigation("Barbershop");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
